### PR TITLE
Stepping tests

### PR DESCRIPTION
**Pull request by ctrlpz**
This pull request contains tests for these stepping operations for actors:

- step-to-message-receiver
- step-to-promise-resolution
- return-from-turn-to-promise-resolution
- step-to-next-turn
- step-to-promise-resolver
- step-to-promise-resolution from `createPromisePrim` primitive 
- step-to-promise-resolution from `whenResolved` primitive
- step-to-promise-resolution from `whenResolvedOnError` primitive
- step-to-promise-resolution from `onError` primitive

### CODE REVIEW

**Comment by smarr** [comment]
@ctrlpz are you sure this isn't integrated already?
Could you please clean up the PR and identify the things that are not integrated yet?
As it is, the branch can't be merged with all these conflicts.

**Comment by ctrlpz** [comment]
ok, I will do a rebase with smarr-master, I don't think these changes are integrated, I looked in smarr-master branch and they are not there

**Comment by smarr** [comment]
Ok, looks much better, but the code doesn't work anymore since this change here: https://github.com/smarr/SOMns/commit/909f5a83a4287b20faf919df600b1593db5b564b

Also, the code has a huge amount of code duplication. I'd rather not merge it like it is. I think it needs a bit more beautifying. Do you want to do that, or would you prefer me to do it?

**Comment by ctrlpz** [comment]
yes, I fixed the stepping according to those changes, now the tests for actors runs fine but I have a problem with the tests of the breakpoints for STM, I'm trying to find the cause

**Comment by ctrlpz** [comment]
I think the stepping tests are ready to merge, I removed the code duplication

**Pull request merged**
