### PR TITLE
Simplify field offset calculation

### LINKED ISSUE #327: Refactor Native Image Support (SubstrateVM) to avoid hard dependency
Looks like @fniephaus managed without it: https://github.com/hpi-swa/graalsqueak/commit/295027cf79b1e888d3c091da3fc462aee22a80bc

So, would probably simplify things.

### PR DESCRIPTION
**Pull request by fniephaus**
SubstrateVM can intercept Unsafe access in order to recalculate field offsets before native image generation. Therefore, it is no longer necessary to maintain a feature and a substitution for this purpose.

This does not remove the SVM dependency as it is still used in [`RuntimeReflectionRegistration.java`](https://github.com/smarr/SOMns/blob/e56f4c2815cef4cae2045a9b05dc1fd190315ba6/src/tools/debugger/RuntimeReflectionRegistration.java#L15). Instead of using `@AutomaticFeature`, it might be possible to provide it as a `Features=` argument for native image. But I have no idea where that code lives and if that'd work.

Closes #327

### CODE REVIEW

**Comment by smarr** [comment]
Thanks a lot. I'll unfortunately not get to this anytime soon.

**Comment by fniephaus** [comment]
This is all I've done in terms of testing:

```
...
native:
     [exec] [som-native:27965]    classlist:   2,854.91 ms
     [exec] [som-native:27965]        (cap):   1,768.80 ms
     [exec] [som-native:27965]        setup:   3,111.26 ms
     [exec] [som-native:27965]   (typeflow):  13,355.46 ms
     [exec] [som-native:27965]    (objects):  10,449.70 ms
     [exec] [som-native:27965]   (features):   2,243.75 ms
     [exec] [som-native:27965]     analysis:  27,243.36 ms
     [exec] [som-native:27965]     (clinit):     499.00 ms
     [exec] 2494 method(s) included for runtime compilation
     [exec] [som-native:27965]     universe:   1,496.93 ms
     [exec] [som-native:27965]      (parse):   2,565.37 ms
     [exec] [som-native:27965]     (inline):   6,446.58 ms
     [exec] [som-native:27965]    (compile):  27,735.81 ms
     [exec] [som-native:27965]      compile:  38,786.97 ms
     [exec] [som-native:27965]        image:   3,141.16 ms
     [exec] [som-native:27965]        write:     809.72 ms
     [exec] [som-native:27965]      [total]:  78,206.24 ms

BUILD SUCCESSFUL
Total time: 1 minute 29 seconds
SOMns (patch-svm*) $ libs/truffle/substratevm/som-native core-lib/Hello.ns
Hello World!
```

**Comment by smarr** [comment]
Thank you!

**Comment by smarr** [comment]
I had hoped that I can remove the SVM core dependency, though, we'll still need it for the Kompos protocol.

**Pull request merged**
