### PR TITLE
Added automatic formatting of TypeScript code

### PR DESCRIPTION
**Pull request by smarr**
This PR applies tsfmt and enables it as test on travis/gitlab ci to check for correct formatting.

@ctrlpz @salenaer @daumayr, please review. And please let me know whether you have any concerns about the change being merged.

### CODE REVIEW

**Comment by ctrlpz** [comment]
I’ve no used these formatters before. In you comment you've said that is enabled as a test, but can we use it when editing? for example, when we save the edited source file VSC will automatically remove unnecessary whitespaces?
Is there any requirement to get this change working that we need to configure in VSC?

**Comment by smarr** [comment]
What I meant to say in the PR description is that the formatter is used to verify that code is properly formatted. So, I added a test, which runs `npm run verify`.

With respect to VS Code, if you haven't enabled whitespace trimming, you really should.
To make sure it is enabled, I added the setting in the VS Code project: https://github.com/smarr/SOMns/pull/167/commits/4c19424a6831b455a89367342855df7f17563490

Autoformatting in VS code is problematic however. It doesn't seem to use exactly the same version as used by `npm run format`.

The format task can be started in VS Code via: cmd+shift+p > run task > format

**Comment by ctrlpz** [comment]
ok I understand, I enabled the trimming of trailing whitespace, thanks for the format commands.

**Comment by smarr** [comment]
So, is this good to merge, or are there outstanding changes I should be aware of?

**Comment by ctrlpz** [comment]
for me is fine, I think is good to have a task that can check the formatting before committing the code.  Although I've not made any changes, @salenaer has done changes in the .ts files, so if he updates I guess he could have some conflicts, but I will help him with the rebase.

**Comment by smarr** [comment]
Let's assume there isn't much reason for him to update beyond 0.4.0.

**Pull request merged**
