### PR TITLE
Use CompilerDirectives::castExact instead of ValueProfiles

### LINKED ISSUE #255: Array storage Strategies: Try to replace value profile with CompilerDirectives.castExact
Should be possible.
Thanks @fniephaus for the hint.
Essentially replace https://github.com/smarr/SOMns/commit/e2431b2acc3e31c4e512157e110795943f2a36f2

This change should be carefully benchmarked.

### PR DESCRIPTION
**Pull request by fniephaus**
The assumption is that performance should remain the same (benchmarks needed for verification). At the same time, this change would simplify code.

Closes #255

### CODE REVIEW

**Comment by fniephaus** [comment]
Turns out the Truffle version that SOMns is using, [does not implement castExact yet](https://github.com/smarr/truffle/blob/3ed852dd7266e1423e848b64673f906da2e70ed7/truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/CompilerDirectives.java).

**Comment by smarr** [comment]
:( damn, yeah, I need to update it, but that's going to take time, which I currently don't have.

**Review by smarr — APPROVED** [review]
Thanks for the PR!

The changes look good to me.
But yeah, I won't be able to merge this before updating Truffle.

And, updating Truffle means I need to update my Truffle changes, adapt the changes for the instrumentation, etc. Last time I tried doing that, I did not manage to get everything working again. So, will take more time.

**Comment by fniephaus** [comment]
No worries, feel free to merge this when done updating Truffle :)
BTW: I've adjusted GraalSqueak and haven't noticed any significant change in performance.

**Comment by smarr** [comment]
@fniephaus Hm, I guess we could do an in-between change, but not sure this is super useful at the moment.

**Comment by smarr** [comment]
And for the record, the `CompilerDirectives.castExact(storage, int.class);` is not correct, because we have an object. Therefore, it should be `CompilerDirectives.castExact(storage, Integer.class);` (as seen in the gitter chat)

**Comment by fniephaus** [comment]
Why shouldn't this be useful at the moment? Performance should remain the same, code is simpler? castExact will only help to remove the remaining ValueProfile. Also, we don't need to it for the plain Integer case, A cast to an unboxed int should do the trick, right?

**Comment by smarr** [comment]
I fixed a couple of compilation issues, and applied the exactCast. Tests are passing, but still waiting for the benchmark results.

**Comment by smarr** [comment]
Results are very noisy. Ups and downs, on peak performance as well as interpreter speed.
Think the measurements aren't very reliable.
Though, they don't indicate a performance problem.
So, I'll merge this since it simplifies the code.

**Pull request merged**
